import argparse
import csv
import json
import os
import random
import sys
from pathlib import Path

import numpy as np
import torch
import cv2

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

import config
from data.dataset import EchoDataset
from models.ef_model import EFModel, infer_ef_head_arch
from pipeline.stage3_phase_detector import Stage3PhaseDetector


def parse_args():
    parser = argparse.ArgumentParser(description="Validate Stage1-3 robustness under temporal perturbations/permutations.")
    parser.add_argument("--checkpoint", type=str, required=True)
    parser.add_argument("--data-dir", type=str, default=config.DATA_DIR)
    parser.add_argument("--split", type=str, default="VAL", choices=["TRAIN", "VAL", "TEST"])
    parser.add_argument("--num-frames", type=int, default=int(getattr(config, "NUM_FRAMES", 64)))
    parser.add_argument("--max-videos", type=int, default=None)
    parser.add_argument("--clip-period", type=int, default=int(getattr(config, "CLIP_PERIOD", 1)))
    parser.add_argument("--clip-eval-mode", type=str, choices=["center", "all"], default="center")
    parser.add_argument("--phase-tolerance", type=int, default=4)
    parser.add_argument(
        "--perturbations",
        type=str,
        default="random_mask,attention_guided_mask,spatial_occlusion,random_permutation,cyclic_shift,reverse",
        help="Comma-separated: random_mask, attention_guided_mask, spatial_occlusion, random_permutation, cyclic_shift, reverse",
    )
    parser.add_argument("--severities", type=str, default="0.10,0.25")
    parser.add_argument("--plots", type=int, default=0, help="Reserved for compatibility; no plots are generated by this script.")
    parser.add_argument("--save-artifacts", action="store_true", help="Save clean/perturbed preview videos and key-frame PNGs.")
    parser.add_argument("--artifact-max-cases", type=int, default=0, help="Max source videos to save artifacts for; 0 means every evaluated video.")
    parser.add_argument("--artifact-fps", type=float, default=12.0)
    parser.add_argument("--spatial-grid", type=int, default=4, help="Grid size for spatial occlusion, e.g. 4 means 4x4 regions.")
    parser.add_argument("--spatial-top-frames", type=int, default=4, help="Number of attention-ranked frames used for spatial occlusion.")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--output-dir", type=str, default=os.path.join("validation", "outputs", "temporal_perturbations"))
    parser.add_argument("--device", type=str, default=("cuda" if torch.cuda.is_available() else "cpu"))
    return parser.parse_args()


def load_model(checkpoint_path, num_frames, device):
    checkpoint = torch.load(checkpoint_path, map_location=device)
    state_dict = checkpoint.get("model_state_dict", checkpoint) if isinstance(checkpoint, dict) else checkpoint
    model = EFModel(num_frames=int(num_frames), ef_head_arch=infer_ef_head_arch(state_dict)).to(device)
    model_state = model.state_dict()
    filtered = {
        key: value
        for key, value in state_dict.items()
        if key in model_state and tuple(value.shape) == tuple(model_state[key].shape)
    }
    incompatible = model.load_state_dict(filtered, strict=False)
    model.eval()
    return model, incompatible


def _parse_csv_list(value, cast=str):
    items = [item.strip() for item in str(value).split(",") if item.strip()]
    return [cast(item) for item in items]


def _summarize_attention(attention):
    attn = attention.detach().float()
    if attn.ndim == 2:
        summary = attn.mean(dim=-1)
    else:
        summary = attn.reshape(-1)
    return summary / summary.sum().clamp_min(1e-8)


def _predict_one(model, video):
    ef_pred, attention, phase_pred = model(video.unsqueeze(0))
    pred_ed, pred_es = Stage3PhaseDetector.predict_indices(phase_pred)
    attn_summary = _summarize_attention(attention[0])
    return {
        "ef_pct": float(ef_pred[0].detach().cpu().item() * 100.0),
        "pred_ed_idx": int(pred_ed[0].detach().cpu().item()),
        "pred_es_idx": int(pred_es[0].detach().cpu().item()),
        "pred_ed_conf": _phase_confidence(phase_pred[0], pred_ed[0], 1),
        "pred_es_conf": _phase_confidence(phase_pred[0], pred_es[0], 2),
        "attention_peak_idx": int(torch.argmax(attn_summary).detach().cpu().item()),
        "attention": attn_summary.detach().cpu(),
    }


def _phase_confidence(phase_output, pred_idx, channel):
    if phase_output.ndim == 2 and phase_output.shape[-1] >= 3:
        probs = torch.softmax(phase_output[:, channel], dim=0)
        return float(probs[int(pred_idx)].detach().cpu().item())
    if phase_output.ndim == 1:
        phase = phase_output.detach().float()
        score = -torch.minimum(torch.abs(phase), torch.abs(phase - 1.0)) if channel == 1 else -torch.abs(phase - 0.5)
        probs = torch.softmax(score, dim=0)
        return float(probs[int(pred_idx)].cpu().item())
    return float("nan")


def _mask_frames(video, frame_indices):
    out = video.clone()
    replacement = video.mean(dim=1, keepdim=True)
    out[:, frame_indices, :, :] = replacement[:, :1, :, :]
    return out


def _denormalize_video(video):
    """Convert a normalized (C,T,H,W) tensor to uint8 RGB frames shaped (T,H,W,3)."""
    tensor = video.detach().float().cpu()
    if bool(getattr(config, "NORMALIZE_INPUT", True)):
        mean = torch.tensor([0.43216, 0.394666, 0.37645], dtype=tensor.dtype).view(3, 1, 1, 1)
        std = torch.tensor([0.22803, 0.22145, 0.216989], dtype=tensor.dtype).view(3, 1, 1, 1)
        tensor = tensor * std + mean
    tensor = tensor.clamp(0.0, 1.0)
    frames = (tensor.permute(1, 2, 3, 0).numpy() * 255.0).round().astype(np.uint8)
    return frames


def _save_video_mp4(frames_rgb, path, fps=12.0):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if len(frames_rgb) == 0:
        return ""
    height, width = frames_rgb[0].shape[:2]
    writer = cv2.VideoWriter(str(path), cv2.VideoWriter_fourcc(*"mp4v"), float(fps), (width, height))
    for frame in frames_rgb:
        writer.write(cv2.cvtColor(frame, cv2.COLOR_RGB2BGR))
    writer.release()
    return str(path)


def _annotate_frame(frame_rgb, label, color=(30, 136, 229)):
    out = frame_rgb.copy()
    cv2.rectangle(out, (0, 0), (out.shape[1], 22), color, thickness=-1)
    cv2.putText(out, str(label), (5, 16), cv2.FONT_HERSHEY_SIMPLEX, 0.45, (255, 255, 255), 1, cv2.LINE_AA)
    return out


def _save_png(frame_rgb, path):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(path), cv2.cvtColor(frame_rgb, cv2.COLOR_RGB2BGR))
    return str(path)


def _spatial_cells(height, width, grid_size):
    grid_size = max(1, int(grid_size))
    cells = []
    for gy in range(grid_size):
        for gx in range(grid_size):
            y0 = int(round(gy * height / grid_size))
            y1 = int(round((gy + 1) * height / grid_size))
            x0 = int(round(gx * width / grid_size))
            x1 = int(round((gx + 1) * width / grid_size))
            cells.append((gy, gx, y0, y1, x0, x1))
    return cells


def _occlude_regions(video, frame_indices, regions):
    out = video.clone()
    for frame_idx in frame_indices:
        for _, _, y0, y1, x0, x1 in regions:
            patch = out[:, int(frame_idx), y0:y1, x0:x1]
            if patch.numel() > 0:
                out[:, int(frame_idx), y0:y1, x0:x1] = patch.mean()
    return out


def _rank_spatial_regions(model, video, clean_ef_pct, frame_indices, grid_size):
    _, _, height, width = video.shape
    cells = _spatial_cells(height, width, grid_size)
    ranked = []
    with torch.no_grad():
        for cell in cells:
            candidate = _occlude_regions(video, frame_indices, [cell])
            pred = _predict_one(model, candidate)
            ranked.append((abs(pred["ef_pct"] - clean_ef_pct), cell))
    ranked.sort(key=lambda item: item[0], reverse=True)
    return [cell for _, cell in ranked]


def _apply_spatial_occlusion(model, video, severity, clean, args):
    t = int(video.shape[1])
    top_frames = max(1, min(t, int(args.spatial_top_frames)))
    frame_indices = torch.argsort(clean["attention"], descending=True)[:top_frames].cpu().numpy().astype(int).tolist()
    ranked_regions = _rank_spatial_regions(
        model=model,
        video=video,
        clean_ef_pct=clean["ef_pct"],
        frame_indices=frame_indices,
        grid_size=int(args.spatial_grid),
    )
    total_regions = max(1, len(ranked_regions))
    region_count = max(1, min(total_regions, int(round(float(severity) * total_regions))))
    selected = ranked_regions[:region_count]
    metadata = {
        "frame_indices": [int(i) for i in frame_indices],
        "region_count": int(region_count),
        "grid_size": int(args.spatial_grid),
        "regions": [
            {"grid_y": int(gy), "grid_x": int(gx), "y0": int(y0), "y1": int(y1), "x0": int(x0), "x1": int(x1)}
            for gy, gx, y0, y1, x0, x1 in selected
        ],
    }
    return _occlude_regions(video, frame_indices, selected), metadata


def _apply_perturbation(video, perturbation, severity, clean_attention, rng):
    t = int(video.shape[1])
    count = max(1, min(t, int(round(float(severity) * t))))
    metadata = {"count": int(count)}

    if perturbation == "random_mask":
        indices = sorted(rng.sample(range(t), count))
        metadata["masked_indices"] = indices
        return _mask_frames(video, indices), metadata

    if perturbation == "attention_guided_mask":
        top = torch.argsort(clean_attention, descending=True)[:count].cpu().numpy().astype(int).tolist()
        indices = sorted(set(top))
        metadata["masked_indices"] = indices
        return _mask_frames(video, indices), metadata

    if perturbation == "random_permutation":
        indices = sorted(rng.sample(range(t), count))
        permuted = indices[:]
        rng.shuffle(permuted)
        out = video.clone()
        out[:, indices, :, :] = video[:, permuted, :, :]
        metadata["source_indices"] = permuted
        metadata["target_indices"] = indices
        return out, metadata

    if perturbation == "cyclic_shift":
        max_shift = max(1, count)
        shift = rng.choice([s for s in range(-max_shift, max_shift + 1) if s != 0])
        metadata["shift"] = int(shift)
        return torch.roll(video, shifts=int(shift), dims=1), metadata

    if perturbation == "reverse":
        metadata["reversed_frames"] = int(t)
        return torch.flip(video, dims=[1]), metadata

    raise ValueError(f"Unsupported perturbation: {perturbation}")


def _save_case_artifacts(output_dir, sample_index, file_stem, perturbation, severity, clean_video, perturbed_video, row, metadata, fps):
    case_dir = Path(output_dir) / "artifacts" / f"{sample_index:05d}_{file_stem}" / f"{perturbation}_sev{float(severity):.2f}".replace(".", "p")
    clean_frames = _denormalize_video(clean_video)
    pert_frames = _denormalize_video(perturbed_video)

    clean_video_path = _save_video_mp4(clean_frames, case_dir / "clean.mp4", fps=fps)
    perturbed_video_path = _save_video_mp4(pert_frames, case_dir / "perturbed.mp4", fps=fps)

    key_indices = {
        "gt_ed": int(row["gt_ed_clip_idx"]),
        "gt_es": int(row["gt_es_clip_idx"]),
        "clean_pred_ed": int(row["clean_pred_ed_idx"]),
        "clean_pred_es": int(row["clean_pred_es_idx"]),
        "perturbed_pred_ed": int(row["perturbed_pred_ed_idx"]),
        "perturbed_pred_es": int(row["perturbed_pred_es_idx"]),
    }
    frame_paths = {}
    for label, idx in key_indices.items():
        idx = int(np.clip(idx, 0, len(clean_frames) - 1))
        frame_paths[f"clean_{label}_frame_path"] = _save_png(clean_frames[idx], case_dir / f"clean_{label}.png")
        frame_paths[f"perturbed_{label}_frame_path"] = _save_png(pert_frames[idx], case_dir / f"perturbed_{label}.png")

    if perturbation == "spatial_occlusion" and metadata.get("frame_indices"):
        overlay = pert_frames[int(metadata["frame_indices"][0])].copy()
        for region in metadata.get("regions", []):
            cv2.rectangle(
                overlay,
                (int(region["x0"]), int(region["y0"])),
                (int(region["x1"]) - 1, int(region["y1"]) - 1),
                (255, 196, 0),
                2,
            )
        frame_paths["spatial_overlay_frame_path"] = _save_png(
            overlay,
            case_dir / "spatial_overlay.png",
        )

    return {
        "clean_video_path": clean_video_path,
        "perturbed_video_path": perturbed_video_path,
        **frame_paths,
    }


def _original_frame(sampled_indices, clip_idx):
    clip_idx = int(np.clip(int(clip_idx), 0, len(sampled_indices) - 1))
    return int(sampled_indices[clip_idx])


def _ci95(values):
    values = np.asarray(values, dtype=np.float64)
    if values.size == 0:
        return [float("nan"), float("nan")]
    if values.size == 1:
        return [float(values[0]), float(values[0])]
    return [float(np.percentile(values, 2.5)), float(np.percentile(values, 97.5))]


def _build_summary(rows, args, perturbations, severities):
    groups = []
    for perturbation in perturbations:
        for severity in severities:
            group = [r for r in rows if r["perturbation"] == perturbation and abs(float(r["severity"]) - float(severity)) < 1e-12]
            if not group:
                continue
            delta_ef = np.array([r["delta_ef_abs_error_pct"] for r in group], dtype=np.float64)
            delta_ed = np.array([r["delta_ed_abs_error_frames"] for r in group], dtype=np.float64)
            delta_es = np.array([r["delta_es_abs_error_frames"] for r in group], dtype=np.float64)
            pred_shift = np.array([abs(r["perturbed_ef_pred_pct"] - r["clean_ef_pred_pct"]) for r in group], dtype=np.float64)
            groups.append(
                {
                    "perturbation": perturbation,
                    "severity": float(severity),
                    "samples": len(group),
                    "clean_ef_mae_pct": float(np.mean([r["clean_ef_abs_error_pct"] for r in group])),
                    "perturbed_ef_mae_pct": float(np.mean([r["perturbed_ef_abs_error_pct"] for r in group])),
                    "delta_ef_mae_pct": float(delta_ef.mean()),
                    "delta_ef_mae_ci95": _ci95(delta_ef),
                    "clean_ed_mae_frames": float(np.mean([r["clean_ed_abs_error_frames"] for r in group])),
                    "perturbed_ed_mae_frames": float(np.mean([r["perturbed_ed_abs_error_frames"] for r in group])),
                    "delta_ed_mae_frames": float(delta_ed.mean()),
                    "delta_ed_mae_ci95": _ci95(delta_ed),
                    "clean_es_mae_frames": float(np.mean([r["clean_es_abs_error_frames"] for r in group])),
                    "perturbed_es_mae_frames": float(np.mean([r["perturbed_es_abs_error_frames"] for r in group])),
                    "delta_es_mae_frames": float(delta_es.mean()),
                    "delta_es_mae_ci95": _ci95(delta_es),
                    "mean_abs_prediction_shift_pct": float(pred_shift.mean()),
                    "ef_prediction_flip_rate_5pct": float(np.mean(pred_shift >= 5.0)),
                    "phase_joint_within_tol_clean": float(np.mean([r["clean_joint_within_tol"] for r in group])),
                    "phase_joint_within_tol_perturbed": float(np.mean([r["perturbed_joint_within_tol"] for r in group])),
                }
            )

    return {
        "groups": groups,
        "config": {
            "checkpoint": os.path.abspath(args.checkpoint),
            "split": args.split,
            "num_frames": int(args.num_frames),
            "clip_period": int(args.clip_period),
            "clip_eval_mode": args.clip_eval_mode,
            "max_videos": args.max_videos,
            "perturbations": perturbations,
            "severities": [float(s) for s in severities],
            "seed": int(args.seed),
            "device": str(args.device),
            "plots_saved": 0,
        },
    }


def _write_outputs(rows, output_dir, args, perturbations, severities):
    if not rows:
        return
    csv_path = Path(output_dir) / "temporal_perturbation_results.csv"
    summary_path = Path(output_dir) / "temporal_perturbation_summary.json"
    fieldnames = sorted({key for row in rows for key in row.keys()})
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    summary = _build_summary(rows, args, perturbations, severities)
    with summary_path.open("w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)


def main():
    args = parse_args()
    rng = random.Random(int(args.seed))
    device = torch.device(args.device)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    perturbations = _parse_csv_list(args.perturbations, str)
    severities = _parse_csv_list(args.severities, float)

    dataset = EchoDataset(
        data_dir=args.data_dir,
        split=args.split,
        num_frames=args.num_frames,
        max_videos=args.max_videos,
        normalize_input=bool(getattr(config, "NORMALIZE_INPUT", True)),
        clip_period=args.clip_period,
        clip_eval_mode=args.clip_eval_mode,
    )
    model, incompatible = load_model(args.checkpoint, args.num_frames, device)
    if incompatible.missing_keys or incompatible.unexpected_keys:
        print(
            f"Warning: checkpoint loaded with key mismatch | missing={len(incompatible.missing_keys)} unexpected={len(incompatible.unexpected_keys)}"
        )

    rows = []
    with torch.no_grad():
        for sample_index in range(len(dataset)):
            meta = dataset.filelist.iloc[sample_index]
            file_stem = str(meta["FileName"]).strip()
            file_name_ext = file_stem + ".avi"
            video_path = os.path.join(args.data_dir, "Videos", file_name_ext)
            ed_orig = int(dataset.phase_dict[file_name_ext]["ed"])
            es_orig = int(dataset.phase_dict[file_name_ext]["es"])
            video, sampled_indices = dataset.load_video(video_path, ed_original=ed_orig, es_original=es_orig)
            ed_idx = dataset._original_to_clip_index(ed_orig, sampled_indices)
            es_idx = dataset._original_to_clip_index(es_orig, sampled_indices)
            ef_gt_pct = float(meta["EF"])

            video = video.to(device)
            clean = _predict_one(model, video)
            clean_ed_abs = abs(clean["pred_ed_idx"] - int(ed_idx))
            clean_es_abs = abs(clean["pred_es_idx"] - int(es_idx))
            clean_ef_abs = abs(clean["ef_pct"] - ef_gt_pct)
            clean_joint = int(clean_ed_abs <= args.phase_tolerance and clean_es_abs <= args.phase_tolerance)

            for perturbation in perturbations:
                for severity in severities:
                    if perturbation == "spatial_occlusion":
                        perturbed_video, perturb_meta = _apply_spatial_occlusion(model, video, severity, clean, args)
                    else:
                        perturbed_video, perturb_meta = _apply_perturbation(
                            video=video,
                            perturbation=perturbation,
                            severity=severity,
                            clean_attention=clean["attention"],
                            rng=rng,
                        )
                    perturbed = _predict_one(model, perturbed_video)
                    pert_ed_abs = abs(perturbed["pred_ed_idx"] - int(ed_idx))
                    pert_es_abs = abs(perturbed["pred_es_idx"] - int(es_idx))
                    pert_ef_abs = abs(perturbed["ef_pct"] - ef_gt_pct)
                    pert_joint = int(pert_ed_abs <= args.phase_tolerance and pert_es_abs <= args.phase_tolerance)

                    row = {
                            "sample_index": sample_index,
                            "file_name": file_name_ext,
                            "perturbation": perturbation,
                            "severity": float(severity),
                            "ef_gt_pct": ef_gt_pct,
                            "gt_ed_clip_idx": int(ed_idx),
                            "gt_es_clip_idx": int(es_idx),
                            "gt_ed_orig_frame": int(ed_orig),
                            "gt_es_orig_frame": int(es_orig),
                            "clean_pred_ed_idx": clean["pred_ed_idx"],
                            "clean_pred_es_idx": clean["pred_es_idx"],
                            "clean_pred_ed_orig_frame": _original_frame(sampled_indices, clean["pred_ed_idx"]),
                            "clean_pred_es_orig_frame": _original_frame(sampled_indices, clean["pred_es_idx"]),
                            "perturbed_pred_ed_idx": perturbed["pred_ed_idx"],
                            "perturbed_pred_es_idx": perturbed["pred_es_idx"],
                            "perturbed_pred_ed_orig_frame": _original_frame(sampled_indices, perturbed["pred_ed_idx"]),
                            "perturbed_pred_es_orig_frame": _original_frame(sampled_indices, perturbed["pred_es_idx"]),
                            "clean_ef_pred_pct": clean["ef_pct"],
                            "perturbed_ef_pred_pct": perturbed["ef_pct"],
                            "clean_ef_abs_error_pct": clean_ef_abs,
                            "perturbed_ef_abs_error_pct": pert_ef_abs,
                            "delta_ef_abs_error_pct": pert_ef_abs - clean_ef_abs,
                            "clean_ed_abs_error_frames": float(clean_ed_abs),
                            "clean_es_abs_error_frames": float(clean_es_abs),
                            "perturbed_ed_abs_error_frames": float(pert_ed_abs),
                            "perturbed_es_abs_error_frames": float(pert_es_abs),
                            "delta_ed_abs_error_frames": float(pert_ed_abs - clean_ed_abs),
                            "delta_es_abs_error_frames": float(pert_es_abs - clean_es_abs),
                            "clean_joint_within_tol": clean_joint,
                            "perturbed_joint_within_tol": pert_joint,
                            "clean_pred_ed_conf": clean["pred_ed_conf"],
                            "clean_pred_es_conf": clean["pred_es_conf"],
                            "perturbed_pred_ed_conf": perturbed["pred_ed_conf"],
                            "perturbed_pred_es_conf": perturbed["pred_es_conf"],
                            "clean_attention_peak_idx": clean["attention_peak_idx"],
                            "perturbed_attention_peak_idx": perturbed["attention_peak_idx"],
                            "perturbation_metadata_json": json.dumps(perturb_meta),
                        }
                    if args.save_artifacts and (args.artifact_max_cases <= 0 or sample_index < args.artifact_max_cases):
                        artifacts = _save_case_artifacts(
                            output_dir=output_dir,
                            sample_index=sample_index,
                            file_stem=file_stem,
                            perturbation=perturbation,
                            severity=severity,
                            clean_video=video,
                            perturbed_video=perturbed_video,
                            row=row,
                            metadata=perturb_meta,
                            fps=args.artifact_fps,
                        )
                        row.update(artifacts)
                    rows.append(row)

            _write_outputs(rows, output_dir, args, perturbations, severities)

    if not rows:
        raise RuntimeError("No perturbation rows were generated")

    csv_path = output_dir / "temporal_perturbation_results.csv"
    summary_path = output_dir / "temporal_perturbation_summary.json"
    _write_outputs(rows, output_dir, args, perturbations, severities)
    summary = _build_summary(rows, args, perturbations, severities)

    print("=" * 90)
    print("TEMPORAL PERTURBATION VALIDATION SUMMARY")
    print("=" * 90)
    print(f"Split: {args.split} | Samples: {len(dataset)} | Rows: {len(rows)}")
    for group in summary["groups"]:
        print(
            f"{group['perturbation']} severity={group['severity']:.2f} | "
            f"delta EF MAE={group['delta_ef_mae_pct']:.2f}% | "
            f"delta ED/ES MAE={group['delta_ed_mae_frames']:.2f}/{group['delta_es_mae_frames']:.2f} fr | "
            f"joint clean/pert={group['phase_joint_within_tol_clean'] * 100:.1f}%/"
            f"{group['phase_joint_within_tol_perturbed'] * 100:.1f}%"
        )
    print(f"Saved rows: {csv_path}")
    print(f"Saved summary: {summary_path}")


if __name__ == "__main__":
    main()
